default_context:
  github_username: bbugyi200
  git_org_name: bbugyi200
  git_repo_name: app
  package_name: app
  pypi_package_name: app
  read_the_docs_domain: app
  package_description: "A test application."
  package_type: application
