name: CI
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose

      - name: Cleanup test artifacts from previous runs.
        run: |
          make clean

      - name: Generate test projects using this cookiecutter.
        run: |
          make test
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [test]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Release a new version if changelog contains unreleased changes.
        run: |
          ./bin/new_release
