name: Labeler

"on":
  push:
    branches:
      - master

permissions:
  # Issues and related comments, assignees, labels, and milestones.
  issues: write

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-delete: false
